In [28]:
import numpy as np
import subprocess

In [24]:
ar = np.arange(0, 20)
print(ar)
print(len(ar))
print(len(ar) // 2)
print(ar[len(ar) // 2])
limit = 5
new_ar = ar[len(ar)//2-limit : len(ar)//2+limit+1]
print(new_ar)
print(len(new_ar))
print(len(new_ar)//2)
print(new_ar[len(new_ar)//2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
20
10
10
[ 5  6  7  8  9 10 11 12 13 14 15]
11
5
10


In [27]:
ar = np.arange(0, 21)
print(ar)
print(len(ar))
print(len(ar) // 2)
print(ar[len(ar) // 2])
limit = 5
new_ar = ar[len(ar)//2-limit : len(ar)//2+limit+1]
print(new_ar)
print(len(new_ar))
print(len(new_ar)//2)
print(new_ar[len(new_ar)//2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
21
10
10
[ 5  6  7  8  9 10 11 12 13 14 15]
11
5
10


In [70]:
proc = subprocess.Popen("ps -e | grep flirt", encoding='utf-8', stdout=subprocess.PIPE, shell=True)

outs = proc.communicate()[0].split('\n')
for line in outs:
    parts = line.split()
    print(parts)
    if len(parts) > 0:
        time = parts[2].split(':')
        print(time)
        secs = int(time[0])*3600 + int(time[1])*60 + int(time[2])
        print(secs)

['15021', 'pts/0', '00:03:38', 'flirt']
['00', '03', '38']
218
['15204', 'pts/0', '00:02:44', 'flirt']
['00', '02', '44']
164
['15967', 'pts/0', '00:01:38', 'flirt']
['00', '01', '38']
98
['16052', 'pts/0', '00:01:33', 'flirt']
['00', '01', '33']
93
['17174', 'pts/0', '00:00:55', 'flirt']
['00', '00', '55']
55
['17269', 'pts/0', '00:00:48', 'flirt']
['00', '00', '48']
48
['17355', 'pts/0', '00:00:44', 'flirt']
['00', '00', '44']
44
['17650', 'pts/0', '00:00:40', 'flirt']
['00', '00', '40']
40
['17950', 'pts/0', '00:00:20', 'flirt']
['00', '00', '20']
20
['18285', 'pts/0', '00:00:12', 'mcflirt']
['00', '00', '12']
12
['19000', 'pts/0', '00:00:00', 'flirt']
['00', '00', '00']
0
[]
